### ISSUE TITLE
"Alias not found" for imported type 

### ISSUE THREAD

**Issue by muelli** [dillonkearns/elm-typescript-interop#5] opened 2018-01-02 14:44 UTC
I'm trying to use elm-ts-interop for my Main.elm which does something like

```elm
import Models exposing (FooModel, BarModel)

port check : FooModel -> Cmd msg

port suggestions : ({ result : List BarModel } -> msg) -> Sub msg
```

it seems to compile file, but the generate file looks like this:

```typescript
// WARNING: Do not manually modify this file. It was generated using:
// https://github.com/dillonkearns/elm-typescript-interop
// Type definitions for Elm ports
export as namespace Elm


export interface App {
  ports: {
    check: {
      subscribe(callback: (data: Alias not found) => void): void
    }
    suggestions: {
      send(data: { result: Alias not found[] }): void
    }
  }
}
    

export namespace Main {
  export function fullscreen(): App
  export function embed(node: HTMLElement | null): App
}
```

When I copy and paste the type into the Main.elm, it seems to work as expected.

However, I expected e-ts-io to work equally fine with the imported type.

**Comment by dillonkearns** [comment] 2018-01-04 17:51
Thank you for reporting the issue @muelli! `elm-typescript-interop` should definitely be erroring out in the CLI instead of putting these messages in the generated file.

I believe the issue in this case is probably that you did not include the source file that defines `FooModel` and `BarModel` as an argument to the command line tool. There is also a known issue right now where when using qualified types (like `MyModule.FooModel`) it is unable to lookup the types. I'd like to support this as well, but it will take some work. But since you're exposing (FooModel), I think the issue is just that you need to include that source file when you run the CLI.

I'd also like to make this less error-prone by inspecting the `elm-package.json` for its source files and including all of those files automatically. Hope that helps, thanks for the feedback!

**Comment by muelli** [comment] 2018-04-25 21:23
can you provide a pointer towards where the "Alias not found" is being determined and written?  Then I can have a look, maybe, whether I can make it error out in that case.

**Comment by dillonkearns** [comment] 2018-09-02 20:09
I made the alias lookup more robust in this latest release. See the [changelog for npm version 0.0.5](https://github.com/dillonkearns/elm-typescript-interop/blob/master/CHANGELOG.md#005---2018-09-02).

Note that I still need to make a couple of changes to get this parsing Elm 0.19 program types properly.

Also, I still will need to make it a little bit more robust to properly do alias lookups when you use the `import Some.Module as MyAlias`. But since this particular issue should be resolved I'll close this thread and we can discuss anything else that comes up on a fresh issue. I would love to get more feedback on how the latest version is working for your project! Thank you!

**Closed as completed by dillonkearns** 2018-09-02 20:09 UTC
Labels: bug

**Comment by muelli** [comment] 2018-10-19 22:11
hrm. unfortunately, now it fails to parse. It seems it's tripping over
```
 subscriptions : Model -> Sub Msg
 subscriptions model =
    Sub.batch
        [
        ]
```

Replacing it by `Sub.none` makes it progress further, but only to then fail somewhere else, i.e. 
```
(.pyenv) ➜ p git:(master) ✗>./node_modules/.bin/elm-typescript-interop 
Could not parse file `assets/elm/LoginApp.elm` at position 63135. Errors:
expected end of input
(.pyenv) ➜ p git:(master) ✗>
```

**Comment by muelli** [comment] 2018-10-29 11:34
hrm. I've opened https://github.com/tunguski/elm-ast/issues/35
